---
- name: create vmalert system group
  group:
    name: vmalert
    system: true
    state: present

- name: create vmalert system user
  user:
    name: vmalert
    system: true
    shell: "/usr/sbin/nologin"
    group: vmalert
    createhome: false

- name: create vmalert configuration directories
  file:
    path: "{{ item }}"
    state: directory
    owner: root
    group: vmalert
    mode: 0770
  with_items:
    - "{{ vmalert_config_dir }}"

- block:
    - name: download vmalert binary to local folder
      become: false
      get_url:
        url: "https://github.com/VictoriaMetrics/VictoriaMetrics/releases/download/v{{ vmalert_version }}/vmutils-v{{ vmalert_version }}.tar.gz"
        dest: "/tmp/vmutils-v{{ vmalert_version }}.tar.gz"
        checksum: "sha256:{{ __vmalert_checksum }}"
      register: _download_archive
      until: _download_archive is succeeded
      retries: 5
      delay: 2
      delegate_to: localhost
      check_mode: false

    - name: unpack vmalert binaries
      become: false
      unarchive:
        src: "/tmp/vmutils-v{{ vmalert_version }}.tar.gz"
        dest: "/tmp"
      delegate_to: localhost
      check_mode: false

    - name: propagate official vmutils binaries
      copy:
        src: "/tmp/{{ item }}"
        dest: "{{ vmalert_binary_install_dir }}/{{ item }}"
        mode: 0755
        owner: root
        group: root
      with_items:
        - vmalert-prod
      notify:
        - restart vmalert

- name: create systemd service unit
  template:
    src: vmalert.service.j2
    dest: /lib/systemd/system/vmalert.service
    owner: root
    group: root
    mode: 0644
  notify:
    - restart vmalert
